/**
 * Generates a per-station nginx geo-block config snippet.
 *
 * Works with the nginx GeoIP2 module. The main nginx.conf includes
 * /etc/nginx/geoblock.d/*.conf via `include /etc/nginx/geoblock.d/*.conf`.
 *
 * Each snippet defines a map variable like $block_<stationId> that
 * evaluates to 1 for blocked countries and 0 otherwise.
 * The Icecast proxy location block checks this variable and returns 403.
 */

export function generateNginxGeoSnippet(
  stationId: string,
  mountPath: string,
  blockedCountryCodes: string[]
): string {
  const varName = `block_${stationId.replace(/-/g, "_")}`;
  const mount = mountPath.startsWith("/") ? mountPath : `/${mountPath}`;

  if (blockedCountryCodes.length === 0) {
    return `# Station ${stationId} (${mount}): no geo-blocks active\n`;
  }

  const lines: string[] = [
    `# Auto-generated geo-block for station: ${stationId} (${mount})`,
    `# Blocked countries: ${blockedCountryCodes.join(", ")}`,
    ``,
    `geo $remote_addr $${varName} {`,
    `  default 0;`,
    ...blockedCountryCodes.map((cc) => `  # ${cc}`),
    `  # Note: actual country lookup requires ngx_http_geoip2_module`,
    `  # Replace the geo block with geoip2 $geoip2_data_country_code { ... }`,
    `  # when the geoip2 module is available.`,
    `}`,
    ``,
    `# To enforce in the proxy location for ${mount}:`,
    `# if ($${varName}) { return 403 "Geo-blocked"; }`,
    ``,
  ];

  return lines.join("\n");
}

/**
 * Generates per-station location snippets for the shared nginx reverse proxy.
 *
 * The base docker/nginx/nginx.conf already defines the server and the shared
 * `upstream icecast_backend`. This function must only emit extra location
 * blocks for stations that have geo restrictions, otherwise nginx will fail to
 * start with duplicate upstream/server definitions.
 */
export function generateNginxIcecastProxy(
  icecastHost: string,
  icecastPort: number,
  stations: Array<{ stationId: string; mountPath: string; blockedCodes: string[] }>
): string {
  const lines: string[] = [
    `# Auto-generated by OpenRadio — per-station geo-block locations`,
    `# Main upstream/server live in docker/nginx/nginx.conf`,
    `# Params retained for compatibility: ${icecastHost}:${icecastPort}`,
    ``,
  ];

  for (const station of stations) {
    if (station.blockedCodes.length === 0) continue;
    const mount = station.mountPath.startsWith("/") ? station.mountPath : `/${station.mountPath}`;
    const varName = `block_${station.stationId.replace(/-/g, "_")}`;

    lines.push(`# Station: ${station.stationId} — blocked: ${station.blockedCodes.join(", ")}`);
    lines.push(`location = ${mount} {`);
    lines.push(`  if ($${varName}) {`);
    lines.push(`    return 403 "This stream is not available in your region.";`);
    lines.push(`  }`);
    lines.push(`  proxy_pass http://icecast_backend;`);
    lines.push(`  proxy_set_header Host $host;`);
    lines.push(`  proxy_set_header X-Real-IP $remote_addr;`);
    lines.push(`  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;`);
    lines.push(`  proxy_set_header X-Forwarded-Proto $scheme;`);
    lines.push(`  proxy_http_version 1.1;`);
    lines.push(`  proxy_buffering off;`);
    lines.push(`  proxy_request_buffering off;`);
    lines.push(`  proxy_cache off;`);
    lines.push(`}`);
    lines.push(``);
  }

  return lines.join("\n") + "\n";
}
