/**
 * Generates a per-station Liquidsoap script.
 *
 * Each station gets its own .liq file that:
 *  - reads its uploaded tracks from /uploads/<stationId>/
 *  - reads any playlist .m3u files from /configs/<stationId>/
 *  - applies a time-based schedule if schedule blocks exist
 *  - falls back to blank() to keep the mount alive
 *  - calls the play-log API on every track change (on_track hook)
 *  - outputs to Icecast on the station's mount path
 */

export type ScheduleEntry = {
  name: string;
  dayOfWeek: number;   // -1 = every day, 0 = Sun … 6 = Sat
  startHour: number;
  startMin: number;
  endHour: number;
  endMin: number;
  playlistId: string | null;
};

export type LiqConfig = {
  stationId: string;
  stationName: string;
  mountPath: string;
  sourcePassword: string;
  icecastHost: string;
  icecastPort: number;
  genre: string;
  description: string;
  appBaseUrl: string;
  pollSecret: string;
  schedules: ScheduleEntry[];
  bitrate?: number;
};

// Escape a string for use inside a Liquidsoap string literal
function liqEscape(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

// Liquidsoap day-of-week: 0=Sunday … 6=Saturday (matches JS)
// time() returns seconds since midnight
function buildTimeCondition(e: ScheduleEntry): string {
  const startSec = e.startHour * 3600 + e.startMin * 60;
  const endSec = e.endHour * 3600 + e.endMin * 60;

  if (e.dayOfWeek === -1) {
    // Every day
    return `(time() >= ${startSec} and time() < ${endSec})`;
  }
  // Liquidsoap uses 1w … 7w for Mon-Sun (1=Mon, 7=Sun)
  // Convert JS day (0=Sun…6=Sat) to Liquidsoap day (1=Mon…7=Sun)
  const liqDay = e.dayOfWeek === 0 ? 7 : e.dayOfWeek;
  return `(weekday() == ${liqDay} and time() >= ${startSec} and time() < ${endSec})`;
}

export function generateLiqScript(cfg: LiqConfig): string {
  const mount = cfg.mountPath.startsWith("/") ? cfg.mountPath : `/${cfg.mountPath}`;
  const bitrate = cfg.bitrate ?? 128;
  const uploadDir = `/uploads/${cfg.stationId}`;
  const configDir = `/configs/${cfg.stationId}`;

  const lines: string[] = [];

  lines.push(`# Auto-generated by OpenRadio — station: ${cfg.stationName}`);
  lines.push(`# DO NOT EDIT — regenerated on every station save`);
  lines.push(`set("log.stdout", true)`);
  lines.push(`set("server.telnet", false)`);
  lines.push(``);

  // on_track handler — POSTs to the play log API
  lines.push(`# Report each track to the play-log API`);
  lines.push(`def on_track_handler(m) =`);
  lines.push(`  title   = m["title"]`);
  lines.push(`  artist  = m["artist"]`);
  lines.push(`  if title != "" then`);
  lines.push(`    body = '{"title":"' ^ string.escape(title) ^ '","artist":"' ^ string.escape(artist) ^ '"}'`);
  lines.push(`    url  = "${liqEscape(cfg.appBaseUrl)}/api/stations/${cfg.stationId}/play-log"`);
  lines.push(`    ignore(http.post(url,`);
  lines.push(`      headers=[("Content-Type","application/json"),("x-poll-secret","${liqEscape(cfg.pollSecret)}")],`);
  lines.push(`      data=body))`);
  lines.push(`  end`);
  lines.push(`end`);
  lines.push(``);

  // Default playlist — all uploaded files shuffled
  lines.push(`# Default playlist from uploaded files`);
  lines.push(`default_playlist = playlist(`);
  lines.push(`  id="station_${cfg.stationId}_default",`);
  lines.push(`  mode="random",`);
  lines.push(`  reload_mode="watch",`);
  lines.push(`  "${uploadDir}")`);
  lines.push(``);

  // Named playlists from schedule entries that have a playlistId
  const namedPlaylists = cfg.schedules
    .filter((e) => e.playlistId)
    .reduce<Map<string, ScheduleEntry>>((acc, e) => {
      if (e.playlistId && !acc.has(e.playlistId)) acc.set(e.playlistId, e);
      return acc;
    }, new Map());

  for (const [plId] of namedPlaylists) {
    const varName = `playlist_${plId.replace(/-/g, "_")}`;
    lines.push(`# Playlist ${plId}`);
    lines.push(`${varName} = playlist(`);
    lines.push(`  id="${varName}",`);
    lines.push(`  mode="random",`);
    lines.push(`  reload_mode="watch",`);
    lines.push(`  "${configDir}/${plId}.m3u")`);
    lines.push(``);
  }

  // Build schedule-aware source
  if (cfg.schedules.length > 0) {
    lines.push(`# Schedule-based source`);
    lines.push(`radio = switch(`);
    lines.push(`  track_sensitive=false,`);
    lines.push(`  [`);
    for (const entry of cfg.schedules) {
      const cond = buildTimeCondition(entry);
      const src = entry.playlistId
        ? `playlist_${entry.playlistId.replace(/-/g, "_")}`
        : `default_playlist`;
      lines.push(`    (${cond}, ${src}),  # ${entry.name}`);
    }
    lines.push(`    ({true}, default_playlist)  # fallback`);
    lines.push(`  ]`);
    lines.push(`)`);
  } else {
    lines.push(`radio = default_playlist`);
  }

  lines.push(``);
  lines.push(`# Attach on_track handler`);
  lines.push(`radio = on_track(on_track_handler, radio)`);
  lines.push(``);

  // Fallback to blank so mount stays alive even when no tracks
  lines.push(`# Keep mount alive even with empty library`);
  lines.push(`radio = fallback(track_sensitive=false, [radio, blank()])`);
  lines.push(``);

  // Output
  lines.push(`# Stream to Icecast`);
  lines.push(`output.icecast(`);
  lines.push(`  %mp3(bitrate=${bitrate}, samplerate=44100, stereo=true),`);
  lines.push(`  host="${liqEscape(cfg.icecastHost)}",`);
  lines.push(`  port=${cfg.icecastPort},`);
  lines.push(`  password="${liqEscape(cfg.sourcePassword)}",`);
  lines.push(`  mount="${liqEscape(mount)}",`);
  lines.push(`  name="${liqEscape(cfg.stationName)}",`);
  lines.push(`  description="${liqEscape(cfg.description)}",`);
  lines.push(`  genre="${liqEscape(cfg.genre)}",`);
  lines.push(`  url="${liqEscape(cfg.appBaseUrl)}",`);
  lines.push(`  radio`);
  lines.push(`)`);

  return lines.join("\n") + "\n";
}
