/**
 * Generates a per-station Liquidsoap script.
 *
 * Architecture: hard-cut scheduling via time-based switch(track_sensitive=false).
 *
 *  - AutoDJ uses the static all_tracks.m3u playlist (fast, no API call).
 *  - Each active schedule block gets its own request.dynamic.list source that
 *    calls /api/internal/sched-track/[stationId]/[blockId].
 *    The sched-track API returns the file path if the block should play (once
 *    per window for TRACK/PODCAST/RECORDING, cycling for PLAYLIST), or an
 *    empty 200 when the block's content is exhausted — making the source
 *    unavailable so the switch falls through to AutoDJ.
 *  - switch(track_sensitive=false) fires at the exact second the time window
 *    opens: no waiting for the current AutoDJ track to finish.
 *  - Live encoder input always overrides everything.
 */

export type ScheduleSourceType =
  | "PLAYLIST"
  | "PODCAST_EPISODE"
  | "RECORDING"
  | "TRACK"
  | "RANDOM_ALL"
  | "LIVE_SLOT";

export type ScheduleEntry = {
  blockId: string;         // DB id of the ScheduleBlock row
  name: string;
  dayOfWeek: number;       // -1 = every day, 0 = Sun … 6 = Sat
  startHour: number;
  startMin: number;
  endHour: number;
  endMin: number;
  sourceType: ScheduleSourceType;
  sourceId: string | null;
  playlistId: string | null;
};

export type LiqConfig = {
  stationId: string;
  stationName: string;
  mountPath: string;
  sourcePassword: string;
  icecastOutputPassword: string;
  icecastHost: string;
  icecastPort: number;
  genre: string;
  description: string;
  appBaseUrl: string;
  pollSecret: string;
  schedules: ScheduleEntry[];
  bitrate?: number;
};

function liqEscape(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

/**
 * Build the Liquidsoap time condition for a schedule entry.
 *
 * Liquidsoap 2.3.x API:
 *   time.local() returns a value with methods:
 *     .hour (int), .min (int), .week_day (int: 0=Sun…6=Sat)
 *
 * Returns a string for a def function body (not a single expression),
 * because `let` bindings in switch condition lambdas need to be in a def.
 * See buildTimeConditionFn() which wraps this in a def for use in the switch.
 */
function buildTimeConditionBody(e: ScheduleEntry): string {
  const startMin = e.startHour * 60 + e.startMin;
  const endMin = e.endHour * 60 + e.endMin;
  const lines: string[] = [];
  lines.push(`  t = time.local()`);
  lines.push(`  now_min = t.hour * 60 + t.min`);
  if (e.dayOfWeek === -1) {
    lines.push(`  now_min >= ${startMin} and now_min < ${endMin}`);
  } else {
    // JS 0=Sun…6=Sat == Liquidsoap week_day 0=Sun…6=Sat
    lines.push(`  t.week_day == ${e.dayOfWeek} and now_min >= ${startMin} and now_min < ${endMin}`);
  }
  return lines.join("\n");
}

export function generateLiqScript(cfg: LiqConfig): string {
  const mount = cfg.mountPath.startsWith("/") ? cfg.mountPath : `/${cfg.mountPath}`;
  const bitrate = cfg.bitrate ?? 128;
  const configDir = `/configs/${cfg.stationId}`;
  const escapedSecret = liqEscape(cfg.pollSecret);
  const escapedBaseUrl = liqEscape(cfg.appBaseUrl);

  const lines: string[] = [];

  lines.push(`# Auto-generated by OpenRadio — station: ${cfg.stationName}`);
  lines.push(`# Hard-cut scheduling: switch(track_sensitive=false) fires at exact window time.`);
  lines.push(`# DO NOT EDIT — regenerated on every station/schedule save.`);
  lines.push(`set("log.stdout", true)`);
  lines.push(`set("server.telnet", false)`);
  lines.push(``);

  // ── on_track handler ──────────────────────────────────────────────────────
  lines.push(`# Report each track to the internal play-log API`);
  lines.push(`def on_track_handler(m) =`);
  lines.push(`  title  = m["title"]`);
  lines.push(`  artist = m["artist"]`);
  lines.push(`  if title != "" then`);
  lines.push(`    body = '{"title":"' ^ string.escape(title) ^ '","artist":"' ^ string.escape(artist) ^ '"}'`);
  lines.push(`    url  = "${escapedBaseUrl}/api/internal/play-log/${cfg.stationId}"`);
  lines.push(`    ignore(http.post(url,`);
  lines.push(`      headers=[("Content-Type","application/json"),("x-poll-secret","${escapedSecret}")],`);
  lines.push(`      data=body))`);
  lines.push(`  end`);
  lines.push(`end`);
  lines.push(``);

  // ── Live input ────────────────────────────────────────────────────────────
  lines.push(`# Live source — external encoder connects here`);
  lines.push(`live_input = input.harbor(`);
  lines.push(`  "/live/${cfg.stationId}",`);
  lines.push(`  port=9000,`);
  lines.push(`  user="source",`);
  lines.push(`  password="${liqEscape(cfg.sourcePassword)}")`);
  lines.push(``);

  // ── AutoDJ — static playlist ──────────────────────────────────────────────
  lines.push(`# AutoDJ — static playlist (fast, no API overhead)`);
  lines.push(`autodj = playlist(`);
  lines.push(`  id="autodj_${cfg.stationId}",`);
  lines.push(`  mode="random",`);
  lines.push(`  reload_mode="watch",`);
  lines.push(`  reload=30,`);
  lines.push(`  "${configDir}/all_tracks.m3u")`);
  lines.push(``);

  // ── Per-schedule-block dynamic sources ────────────────────────────────────
  // Only emit sources for blocks that need their own API call
  // (RANDOM_ALL → autodj directly in the switch; LIVE_SLOT → live_input)
  const scheduledBlocks = cfg.schedules.filter(
    (e) => e.sourceType !== "RANDOM_ALL" && e.sourceType !== "LIVE_SLOT",
  );

  if (scheduledBlocks.length > 0) {
    lines.push(`# Per-schedule-block dynamic sources`);
    lines.push(`# Each block calls its own sched-track API endpoint.`);
    lines.push(`# Returning an empty body makes the source unavailable → switch falls to AutoDJ.`);
    lines.push(``);
  }

  for (let i = 0; i < cfg.schedules.length; i++) {
    const entry = cfg.schedules[i];
    if (entry.sourceType === "RANDOM_ALL" || entry.sourceType === "LIVE_SLOT") continue;

    const safeId = `sched_${i}_${cfg.stationId.replace(/-/g, "_")}`;
    const apiUrl = `${cfg.appBaseUrl}/api/internal/sched-track/${cfg.stationId}/${entry.blockId}?secret=${cfg.pollSecret}`;

    lines.push(`# Block ${i}: "${entry.name}" [${entry.sourceType}]`);
    lines.push(`def get_sched_${i}() =`);
    lines.push(`  cmd = "curl --silent --show-error --fail --max-time 5 --retry 2 --retry-delay 1 '${liqEscape(apiUrl)}'"`);
    lines.push(`  result = process.read.lines(cmd)`);
    lines.push(`  uri = string.trim(list.hd(default="", result))`);
    lines.push(`  if uri == "" then`);
    lines.push(`    log("[sched] Block ${i} (${entry.name}) has no content — using AutoDJ")`);
    lines.push(`    []`);
    lines.push(`  else`);
    lines.push(`    log("[sched] Block ${i} (${entry.name}): #{uri}")`);
    lines.push(`    [request.create(uri)]`);
    lines.push(`  end`);
    lines.push(`end`);
    lines.push(`${safeId} = request.dynamic.list(id="${safeId}", get_sched_${i})`);
    lines.push(``);
  }

  // ── Hard-cut time-based switch ────────────────────────────────────────────
  if (cfg.schedules.length > 0) {
    lines.push(`# Time-condition functions for each schedule block`);
    lines.push(`# Using def functions so time.local() can be called cleanly.`);
    for (let i = 0; i < cfg.schedules.length; i++) {
      const entry = cfg.schedules[i];
      lines.push(`def sched_time_${i}() =`);
      lines.push(buildTimeConditionBody(entry));
      lines.push(`end`);
      lines.push(``);
    }

    lines.push(`# Hard-cut scheduler: switch(track_sensitive=false) fires at exact window time.`);
    lines.push(`# AutoDJ is cut immediately when a scheduled window opens.`);
    lines.push(`# When the scheduled source is exhausted (empty from API), the switch falls`);
    lines.push(`# through to AutoDJ for the rest of the window.`);
    lines.push(`radio = switch(`);
    lines.push(`  track_sensitive=false,`);
    lines.push(`  [`);
    for (let i = 0; i < cfg.schedules.length; i++) {
      const entry = cfg.schedules[i];
      let src: string;
      if (entry.sourceType === "RANDOM_ALL") {
        src = "autodj";
      } else if (entry.sourceType === "LIVE_SLOT") {
        src = "live_input";
      } else {
        src = `sched_${i}_${cfg.stationId.replace(/-/g, "_")}`;
      }
      lines.push(`    (sched_time_${i}, ${src}),  # ${entry.name}`);
    }
    lines.push(`    ({true}, autodj)`);
    lines.push(`  ]`);
    lines.push(`)`);
  } else {
    lines.push(`radio = autodj`);
  }

  lines.push(``);

  // ── Transitions ───────────────────────────────────────────────────────────
  lines.push(`# Skip silent gaps, short crossfade`);
  lines.push(`radio = blank.skip(max_blank=0.35, threshold=-48.0, track_sensitive=false, radio)`);
  lines.push(`radio = crossfade(duration=0.12, fade_in=0.04, fade_out=0.04, radio)`);
  lines.push(``);
  lines.push(`# Attach play-log handler`);
  lines.push(`radio = source.on_track(radio, on_track_handler)`);
  lines.push(``);

  // ── Live override ─────────────────────────────────────────────────────────
  lines.push(`# Live encoder takes absolute priority`);
  lines.push(`radio = fallback(track_sensitive=false, [live_input, radio, blank()])`);
  lines.push(``);

  // ── Buffer ────────────────────────────────────────────────────────────────
  lines.push(`radio = mksafe(buffer(buffer=8.0, max=30.0, fallible=false, radio))`);
  lines.push(``);

  // ── Icecast output ────────────────────────────────────────────────────────
  lines.push(`output.icecast(`);
  lines.push(`  %mp3(bitrate=${bitrate}, samplerate=44100, stereo=true),`);
  lines.push(`  host="${liqEscape(cfg.icecastHost)}",`);
  lines.push(`  port=${cfg.icecastPort},`);
  lines.push(`  password="${liqEscape(cfg.icecastOutputPassword)}",`);
  lines.push(`  mount="${liqEscape(mount)}",`);
  lines.push(`  name="${liqEscape(cfg.stationName)}",`);
  lines.push(`  description="${liqEscape(cfg.description)}",`);
  lines.push(`  genre="${liqEscape(cfg.genre)}",`);
  lines.push(`  url="${liqEscape(cfg.appBaseUrl)}",`);
  lines.push(`  radio`);
  lines.push(`)`);

  return lines.join("\n") + "\n";
}
